### ISSUE TITLE
RUN apk update operation timed out

### ISSUE THREAD

**Issue by hitaiji** [YoshinoriN/docker-redmine-orchestration#26] opened 2017-03-13 11:37 UTC
"RUN apk update" seems to time out when building ./redmine/redmine /Dockerfile

```
 # docker-compose build
```

```
................................
................................
Building redmine
Step 1/10 : FROM ruby:2.3.3-alpine
2.3.3-alpine: Pulling from library/ruby
709515475419: Pull complete
7fb3cefb04d0: Pull complete
a1cb78049632: Pull complete
767afe4d82f3: Pull complete
094c4371f371: Pull complete
Digest: sha256:aac3df0199b6ca5ce2870c56a87421643139244e26633fa050713fbbbee52a13
Status: Downloaded newer image for ruby:2.3.3-alpine
 ---> af89cacd44cb
Step 2/10 : MAINTAINER YoshinoriN
 ---> Running in 81a913b724d8
 ---> 2fa0e67a8c5e
Removing intermediate container 81a913b724d8
Step 3/10 : RUN apk update --no-cache   && apk add --no-cache --virtual build-dependencies libffi-dev build-base   && apk add --no-cache mysql-client tzdata mariadb-dev=10.1.21-r0 linux-headers=4.4.6-r1 imagemagick-dev=6.9.5.9-r1   && apk add --no-cache git   && mkdir -p /usr/src/app/redmine   && mkdir -p /usr/src/app/redmine/tmp/pids
 ---> Running in b8949029b162
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/main: operation timed out
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz: operation timed out
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/community: operation timed out
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz: operation timed out
2 errors; 32 distinct packages available
ERROR: Service 'redmine' failed to build: The command '/bin/sh -c apk update --no-cache   && apk add --no-cache --virtual build-dependencies libffi-dev build-base   && apk add --no-cache mysql-client tzdata mariadb-dev=10.1.21-r0 linux-headers=4.4.6-r1 imagemagick-dev=6.9.5.9-r1   && apk add --no-cache git   && mkdir -p /usr/src/app/redmine   && mkdir -p /usr/src/app/redmine/tmp/pids' returned a non-zero code: 2
```

**Comment by yoshinorin** [comment] 2017-03-24 02:49
@hitaiji

Sorry for my late reply.
I can't reproduce this phenomenon.

I think this problem may be caused by host machine network problem.
Is it possible to connect to `http://dl-cdn.alpinelinux.org/alpine/v3.4/main` from your host machine ? (not from docker container) 

eg) below is confirm to connect using by wget command.

```sh
wget http://dl-cdn.alpinelinux.org/alpine/v3.4/main

--2017-03-24 11:20:13--  http://dl-cdn.alpinelinux.org/alpine/v3.4/main
Resolving dl-cdn.alpinelinux.org (dl-cdn.alpinelinux.org)... 151.101.0.249, 151.101.192.249, 151.101.64.249, ...
Connecting to dl-cdn.alpinelinux.org (dl-cdn.alpinelinux.org)|151.101.0.249|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://dl-4.alpinelinux.org/alpine/v3.4/main/ [following]
--2017-03-24 11:20:13--  http://dl-4.alpinelinux.org/alpine/v3.4/main/
Resolving dl-4.alpinelinux.org (dl-4.alpinelinux.org)... 74.117.189.114
Connecting to dl-4.alpinelinux.org (dl-4.alpinelinux.org)|74.117.189.114|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1830 (1.8K) [text/html]
Saving to: ‘main.2’

100%[===================================================================================================================================>] 1,830       --.-K/s   in 0s

2017-03-24 11:20:14 (102 MB/s) - ‘main.2’ saved [1830/1830]
```

**Comment by yoshinorin** [comment] 2017-07-22 06:35
@hitaiji

May I close it ?

**Closed as completed** 2017-07-24 16:16 UTC
